import type { CatalystFeed } from "./types";

const demoSourceUrl = "https://example.com/uk-market-heatmap-demo";

export const DEMO_CATALYST_FEED: CatalystFeed = {
  asOf: "2026-08-20T12:00:00.000Z",
  isDemo: true,
  sourceLabel: "Static demo catalysts — not live news",
  catalysts: [
    {
      id: "demo-azn-ma-001",
      symbol: "AZN",
      headline: "Demo scenario: AstraZeneca enters talks for a bolt-on oncology acquisition",
      category: "M&A",
      publishedAt: "2026-08-20T09:00:00.000Z",
      sourceName: "Demo Newswire",
      sourceUrl: demoSourceUrl,
      summary: "Illustrative acquisition catalyst showing how a material strategic event would appear on the heatmap.",
      importance: "high",
    },
    {
      id: "demo-azn-clinical-002",
      symbol: "AZN",
      headline: "Demo scenario: oncology study meets its primary endpoint",
      category: "Clinical",
      publishedAt: "2026-08-19T10:00:00.000Z",
      sourceName: "Demo Newswire",
      sourceUrl: demoSourceUrl,
      summary: "Illustrative positive late-stage clinical readout with potential implications for the product pipeline.",
      importance: "medium",
    },
    {
      id: "demo-azn-regulatory-003",
      symbol: "AZN",
      headline: "Demo scenario: regulator accepts an expanded indication filing",
      category: "Regulatory",
      publishedAt: "2026-08-17T09:30:00.000Z",
      sourceName: "Demo Newswire",
      sourceUrl: demoSourceUrl,
      summary: "Illustrative filing milestone included as a low-importance detail-panel item.",
      importance: "low",
    },
    {
      id: "demo-shel-earnings-001",
      symbol: "SHEL",
      headline: "Demo scenario: Shell reports stronger-than-expected quarterly cash generation",
      category: "Earnings",
      publishedAt: "2026-08-20T07:30:00.000Z",
      sourceName: "Demo Newswire",
      sourceUrl: demoSourceUrl,
      summary: "Illustrative results catalyst focused on operating cash flow and upstream performance.",
      importance: "high",
    },
    {
      id: "demo-shel-dividend-002",
      symbol: "SHEL",
      headline: "Demo scenario: board reiterates progressive dividend policy",
      category: "Dividend",
      publishedAt: "2026-08-18T14:00:00.000Z",
      sourceName: "Demo Newswire",
      sourceUrl: demoSourceUrl,
      summary: "Illustrative capital-return update for the company detail panel.",
      importance: "medium",
    },
    {
      id: "demo-hsba-buyback-001",
      symbol: "HSBA",
      headline: "Demo scenario: HSBC announces an additional share buyback",
      category: "Buyback",
      publishedAt: "2026-08-20T08:00:00.000Z",
      sourceName: "Demo Newswire",
      sourceUrl: demoSourceUrl,
      summary: "Illustrative capital-distribution catalyst following a stronger capital position.",
      importance: "high",
    },
    {
      id: "demo-hsba-earnings-002",
      symbol: "HSBA",
      headline: "Demo scenario: HSBC earnings exceed consensus expectations",
      category: "Earnings",
      publishedAt: "2026-08-19T06:00:00.000Z",
      sourceName: "Demo Newswire",
      sourceUrl: demoSourceUrl,
      summary: "Illustrative earnings surprise driven by revenue resilience and controlled credit costs.",
      importance: "medium",
    },
    {
      id: "demo-hsba-management-003",
      symbol: "HSBA",
      headline: "Demo scenario: regional leadership responsibilities are reorganised",
      category: "Management",
      publishedAt: "2026-08-14T11:00:00.000Z",
      sourceName: "Demo Newswire",
      sourceUrl: demoSourceUrl,
      summary: "Illustrative management update retained for the seven-day detail view.",
      importance: "low",
    },
    {
      id: "demo-rr-contract-001",
      symbol: "RR.",
      headline: "Demo scenario: Rolls-Royce secures a multi-year engine services contract",
      category: "Contract",
      publishedAt: "2026-08-20T10:00:00.000Z",
      sourceName: "Demo Newswire",
      sourceUrl: demoSourceUrl,
      summary: "Illustrative long-term service agreement supporting future civil aerospace revenue visibility.",
      importance: "high",
    },
    {
      id: "demo-rr-guidance-002",
      symbol: "RR.",
      headline: "Demo scenario: Rolls-Royce raises full-year cash flow guidance",
      category: "Guidance",
      publishedAt: "2026-08-18T08:00:00.000Z",
      sourceName: "Demo Newswire",
      sourceUrl: demoSourceUrl,
      summary: "Illustrative guidance upgrade reflecting improved operating performance.",
      importance: "medium",
    },
    {
      id: "demo-bae-contract-001",
      symbol: "BA.",
      headline: "Demo scenario: BAE Systems receives a major defence programme award",
      category: "Contract",
      publishedAt: "2026-08-19T13:00:00.000Z",
      sourceName: "Demo Newswire",
      sourceUrl: demoSourceUrl,
      summary: "Illustrative contract award expected to add to the order backlog over several years.",
      importance: "high",
    },
    {
      id: "demo-bae-ma-002",
      symbol: "BA.",
      headline: "Demo scenario: BAE Systems evaluates a specialist technology acquisition",
      category: "M&A",
      publishedAt: "2026-08-16T10:00:00.000Z",
      sourceName: "Demo Newswire",
      sourceUrl: demoSourceUrl,
      summary: "Illustrative acquisition interest included in the seven-day catalyst window.",
      importance: "medium",
    },
    {
      id: "demo-gsk-clinical-001",
      symbol: "GSK",
      headline: "Demo scenario: GSK vaccine candidate delivers positive phase-three data",
      category: "Clinical",
      publishedAt: "2026-08-20T06:00:00.000Z",
      sourceName: "Demo Newswire",
      sourceUrl: demoSourceUrl,
      summary: "Illustrative pivotal-trial result supporting a future regulatory submission.",
      importance: "high",
    },
    {
      id: "demo-gsk-regulatory-002",
      symbol: "GSK",
      headline: "Demo scenario: GSK receives a regulatory review milestone",
      category: "Regulatory",
      publishedAt: "2026-08-18T11:00:00.000Z",
      sourceName: "Demo Newswire",
      sourceUrl: demoSourceUrl,
      summary: "Illustrative regulatory catalyst for a priority pipeline asset.",
      importance: "medium",
    },
  ],
};
